name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install LLVM
      run: |
        wget https://raw.githubusercontent.com/Longhanks/github-actions-ci-scripts/master/ubuntu-18.04-install-llvm.sh
        sudo bash ./ubuntu-18.04-install-llvm.sh
        rm ubuntu-18.04-install-llvm.sh
    - name: Install cmake
      run: |
        wget https://raw.githubusercontent.com/Longhanks/github-actions-ci-scripts/master/linux-install-cmake.sh
        sudo bash ./linux-install-cmake.sh
        rm linux-install-cmake.sh
    - name: Install ninja
      run: |
        wget https://raw.githubusercontent.com/Longhanks/github-actions-ci-scripts/master/linux-install-ninja.sh
        sudo bash ./linux-install-ninja.sh
        rm linux-install-ninja.sh
    - name: Install Qt
      run: |
        wget https://raw.githubusercontent.com/Longhanks/github-actions-ci-scripts/master/linux-install-qt.sh
        sudo bash ./linux-install-qt.sh
        rm linux-install-qt.sh
    - name: Install Qt Creator
      run: |
        wget https://raw.githubusercontent.com/Longhanks/github-actions-ci-scripts/master/linux-install-qtcreator.sh
        sudo bash ./linux-install-qtcreator.sh
        rm linux-install-qtcreator.sh
    - name: Download Qt Creator source
      run: |
        wget https://raw.githubusercontent.com/Longhanks/github-actions-ci-scripts/master/linux-download-qtcreator-src.sh
        sudo bash ./linux-download-qtcreator-src.sh
        rm linux-download-qtcreator-src.sh
    - name: Configure
      run: |
        wget https://raw.githubusercontent.com/Longhanks/github-actions-ci-scripts/master/linux-generate-qtcreator-plugin-buildsystem.sh
        bash ./linux-generate-qtcreator-plugin-buildsystem.sh
        rm linux-generate-qtcreator-plugin-buildsystem.sh
    - name: Build
      run: |
        cd build
        ninja
    - name: Deploy
      run: |
        cd build
        ninja install
    - name: Prepare artifact
      run: |
        cd build
        mkdir artifact
        cp libtabs.so artifact/libtabs.so
    - uses: actions/upload-artifact@v1
      with:
        name: libtabs.so
        path: build/artifact

  build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Install cmake
      shell: cmd
      run: |
        curl -L https://raw.githubusercontent.com/Longhanks/github-actions-ci-scripts/master/windows-install-cmake.bat -o windows-install-cmake.bat
        call windows-install-cmake.bat
        del windows-install-cmake.bat
    - name: Install ninja
      shell: cmd
      run: |
        curl -L https://raw.githubusercontent.com/Longhanks/github-actions-ci-scripts/master/windows-install-ninja.bat -o windows-install-ninja.bat
        call windows-install-ninja.bat
        del windows-install-ninja.bat
    - name: Install Qt
      shell: cmd
      run: |
        curl -L https://raw.githubusercontent.com/Longhanks/github-actions-ci-scripts/master/windows-install-qt.bat -o windows-install-qt.bat
        call windows-install-qt.bat
        del windows-install-qt.bat
    - name: Install Qt Creator
      shell: cmd
      run: |
        curl -L https://raw.githubusercontent.com/Longhanks/github-actions-ci-scripts/master/windows-install-qtcreator.bat -o windows-install-qtcreator.bat
        call windows-install-qtcreator.bat
        del windows-install-qtcreator.bat
    - name: Download Qt Creator source
      shell: cmd
      run: |
        curl -L https://raw.githubusercontent.com/Longhanks/github-actions-ci-scripts/master/windows-download-qtcreator-src.bat -o windows-download-qtcreator-src.bat
        call windows-download-qtcreator-src.bat
        del windows-download-qtcreator-src.bat
    - name: Configure
      shell: cmd
      run: |
        curl -L https://raw.githubusercontent.com/Longhanks/github-actions-ci-scripts/master/windows-generate-qtcreator-plugin-buildsystem.bat -o windows-generate-qtcreator-plugin-buildsystem.bat
        call windows-generate-qtcreator-plugin-buildsystem.bat
        del windows-generate-qtcreator-plugin-buildsystem.bat
    - name: Build
      shell: cmd
      run: |
        cd build
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        ..\ninja.exe
    - name: Deploy
      run: |
        cd build
        ..\ninja.exe install
    - name: Prepare artifact
      shell: cmd
      run: |
        cd build
        mkdir artifact
        copy tabs.dll artifact\tabs.dll
    - uses: actions/upload-artifact@v1
      with:
        name: tabs.dll
        path: build/artifact
